"""Export a run: Markdown dossier, CSV tables, and a complete machine-readable run.json.

Every sentence in the dossier is a template filled from computed facts. No prose is
generated by a model, so no number can appear here that the engine did not compute.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

from .concepts import METRICS
from .engine import Run, code_version, outputs_digest
from .models import FactStatus
from .normalize import Dataset

# ----------------------------------------------------------------------------- formatting


def money(v: float | None) -> str:
    if v is None:
        return "—"
    from decimal import ROUND_HALF_UP, Decimal

    a = abs(v)

    def r(x: float, places: str) -> str:  # half-up on the decimal value, not binary-float half-even
        return f"{Decimal(repr(x)).quantize(Decimal(places), rounding=ROUND_HALF_UP):,}"
    s = f"{r(a / 1e9, '0.1')}bn" if a >= 1e9 else f"{r(a / 1e6, '1')}m" if a >= 1e6 else r(a, "1")
    return f"-${s}" if v < 0 else f"${s}"


def pct(v: float | None, signed: bool = False) -> str:
    if v is None:
        return "—"
    return f"{v * 100:+.1f}%" if signed else f"{v * 100:.1f}%"


def times(v: float | None) -> str:
    return "—" if v is None else f"{v:.2f}x"


def per_share(v: float | None) -> str:
    return "—" if v is None else f"${v:.2f}"


def shares(v: float | None) -> str:
    return "—" if v is None else f"{v / 1e6:,.0f}m"


FORMAT = {"USD": money, "pure": pct, "USD/shares": per_share, "shares": shares}

# metric -> (display label, formatter) for dossier tables
ROWS = {
    "growth": [("revenue", "Revenue", money), ("revenue_growth", "Revenue growth", lambda v: pct(v, True)),
               ("gross_margin", "Gross margin", pct), ("operating_margin", "Operating margin", pct),
               ("net_margin", "Net margin", pct), ("rnd_intensity", "R&D / revenue", pct)],
    "eps": [("net_income", "Net income", money), ("shares_diluted", "Diluted shares (wtd. avg.)", shares),
            ("eps_diluted", "Diluted EPS", per_share), ("eps_growth", "EPS growth", lambda v: pct(v, True)),
            ("diluted_share_change", "Diluted share change", lambda v: pct(v, True))],
    "cash": [("cfo", "Operating cash flow", money), ("cash_conversion", "CFO / net income", times),
             ("capex", "Capex (cash)", money), ("fcf", "Cash FCF (CFO - capex)", money),
             ("fcf_margin", "FCF margin", pct), ("fcf_after_sbc", "FCF after SBC", money)],
    "investment": [("capex_intensity", "Capex / revenue", pct), ("dna", "Depreciation (as tagged; see definitions)", money),
                   ("capex_to_depreciation", "Capex / depreciation", times)],
    "quality": [("sbc", "Stock-based compensation", money), ("sbc_intensity", "SBC / revenue", pct),
                ("nonoperating_share_of_pretax", "Non-operating income / pretax", pct),
                ("effective_tax_rate", "Effective tax rate", pct),
                ("roic", "ROIC (proposed definition)", pct), ("buybacks", "Buybacks", money),
                ("dividends", "Dividends", money), ("payout_to_fcf", "Buybacks + dividends / FCF", pct),
                ("total_debt", "Debt incl. finance leases", money), ("liquid_investments", "Cash + marketable securities", money),
                ("net_debt", "Net debt (negative = net cash)", money),
                ("operating_lease_liability", "Operating leases (excluded from debt)", money)],
}

STATUS_MARK = {FactStatus.REPORTED: "", FactStatus.DERIVED: "", FactStatus.ANALYST_ADJUSTED: "†",
               FactStatus.MISSING: "", FactStatus.CONFLICTING: "‼"}


UNIT_TEXT = {money: "USD", pct: "%", times: "x", per_share: "USD/share", shares: "shares"}


def _table(ds: Dataset, rows, labels=None, lines: dict | None = None) -> str:
    """Values with period ends, units, and each row's definition or source (PRD section 9)."""
    labels = labels or ds.labels
    lines = lines or {}
    ends = []
    for lab in labels:
        f = ds.facts.get(f"revenue@{lab}")
        ends.append(f"{lab} ({f.period_end:%b %d, %Y})" if f else lab)
    out = ["| Metric | Unit | " + " | ".join(ends) + " | Definition / source |", "|---|---|" + "---:|" * len(labels) + "---|"]
    for metric, name, fmt in rows:
        cells, source = [], ""
        for lab in labels:
            f = ds.facts.get(f"{metric}@{lab}")
            if f is None:
                cells.append("—")
                continue
            if f.value is None and f.status == FactStatus.MISSING and f.formula:
                cells.append("n/a")  # suppressed: a formula exists but an input or denominator does not allow it
            else:
                cells.append(fmt(f.value) + STATUS_MARK.get(f.status, ""))
        last = next((ds.facts.get(f"{metric}@{lab}") for lab in reversed(labels) if ds.facts.get(f"{metric}@{lab}")), None)
        if last is not None and last.formula and last.status.value in ("derived", "missing"):
            source = f"`{last.formula}`"
        elif last is not None and last.sources:
            line = lines.get(last.key)
            source = f"{last.sources[0].locator}" + (f" · '{line}'" if line else "")
        unit = UNIT_TEXT.get(fmt, "%")
        out.append(f"| {name} | {unit} | " + " | ".join(cells) + f" | {source} |")
    return "\n".join(out)


def _v(ds: Dataset, metric: str, label: str) -> float | None:
    return ds.value(metric, label)


# ----------------------------------------------------------------------------- narrative


def _growth_sentences(ds: Dataset) -> list[str]:
    a, b = ds.labels[0], ds.labels[-1]
    s = []
    cagr = _v(ds, "revenue_cagr", b)
    if cagr is not None:
        s.append(f"Revenue went from {money(_v(ds, 'revenue', a))} in {a} to {money(_v(ds, 'revenue', b))} in {b}, "
                 f"a compound annual rate of {pct(cagr)} over {len(ds.labels) - 1} years.")
    om_a, om_b = _v(ds, "operating_margin", a), _v(ds, "operating_margin", b)
    if om_a is not None and om_b is not None:
        direction = "expanded" if om_b > om_a else "contracted" if om_b < om_a else "was unchanged"
        s.append(f"Operating margin {direction} from {pct(om_a)} to {pct(om_b)} ({(om_b - om_a) * 1e4:+.0f} bp).")
    return s


def _eps_sentences(run: Run) -> list[str]:
    s = []
    for row in run.eps_bridge:
        if row["status"] != "ok":
            s.append(f"{row['period']}: bridge {row['status']} ({row['reason']}).")
            continue
        total = row["from_earnings_log"] + row["from_share_count_log"] + row["residual_log"]
        earn, share = row["from_earnings_log"], row["from_share_count_log"]
        if total > 0 and earn > 0 and share > 0:
            why = f" — share-count reduction explains {pct(share / total)} of EPS growth (log basis)"
        elif total > 0 and earn <= 0 < share:
            why = " — net income fell; EPS rose only because the share count fell"
        else:
            why = ""
        s.append(
            f"{row['period']}: diluted EPS {pct(row['reported_eps_factor'] - 1, True)}; net income "
            f"{pct(row['net_income_factor'] - 1, True)}, diluted shares {pct(row['share_factor'] - 1, True)}"
            + why + f". It was bought with {money(row['buybacks'])} of repurchases while SBC was {money(row['sbc'])}.")
    return s


def _what_if_sentences(run: Run) -> list[str]:
    b = run.reported.labels[-1]
    rep, alt = _v(run.reported, "eps_diluted", b), _v(run.what_if, "eps_diluted", b)
    grow_r, grow_a = _v(run.reported, "eps_growth", b), _v(run.what_if, "eps_growth", b)
    if rep is None or alt is None or abs(rep - alt) < 0.005:
        return []
    prev = run.reported.labels[-2] if len(run.reported.labels) > 1 else b
    ids = sorted({a.id for a in run.adjustments if a.fiscal_label in (b, prev) and a.metric == "net_income"})
    return [f"If the PROPOSED net-income entries for {prev} and {b} were approved ({', '.join(ids)}), diluted EPS would be "
            f"{per_share(alt)} instead of {per_share(rep)}, and EPS growth {pct(grow_a, True)} instead of "
            f"{pct(grow_r, True)}. None are approved yet; this is a preview for the team's review."]


def _cash_sentences(ds: Dataset) -> list[str]:
    a, b = ds.labels[0], ds.labels[-1]
    s = []
    f_a, f_b, ni_a, ni_b = _v(ds, "fcf", a), _v(ds, "fcf", b), _v(ds, "net_income", a), _v(ds, "net_income", b)
    if None not in (f_a, f_b, ni_a, ni_b) and ni_a > 0 and f_a > 0:
        s.append(f"Net income changed {pct(ni_b / ni_a - 1, True)} from {a} to {b}; cash FCF changed "
                 f"{pct(f_b / f_a - 1, True)} ({money(f_a)} to {money(f_b)}).")
    c_a, c_b = _v(ds, "capex", a), _v(ds, "capex", b)
    if c_a and c_b:
        s.append(f"Capex went from {money(c_a)} to {money(c_b)} ({c_b / c_a:.1f}x), reaching "
                 f"{pct(_v(ds, 'capex_intensity', b))} of revenue and {times(_v(ds, 'capex_to_depreciation', b))} depreciation in {b}.")
    return s


# ----------------------------------------------------------------------------- run payload


def _fact_rows(ds: Dataset, recon_by_key: dict) -> list[dict]:
    out = []
    for key, f in sorted(ds.facts.items()):
        src = f.sources[0] if f.sources else None
        r = recon_by_key.get(key)
        out.append({
            "key": key, "metric": f.metric, "fiscal_label": f.fiscal_label, "value": f.value, "unit": f.unit,
            "status": f.status.value, "period_start": str(f.period_start or ""), "period_end": str(f.period_end),
            "formula": f.formula or "", "inputs": ";".join(f.inputs),
            "currency": f.currency or "", "scale": f.scale,
            "accession": src.accession if src else "", "form": src.form if src else "",
            "filed": str(src.filed) if src else "", "accepted": (src.accepted or "") if src else "",
            "retrieved_at": src.retrieved_at if src else "", "locator": src.locator if src else "",
            "candidates": ";".join(f"{c:g}" for c in f.candidates),
            "source_url": src.url if src else "", "snapshot_id": src.snapshot_id if src else "",
            "reconciliation": r.outcome if r else "", "statement_line": (r.line or "") if r else "",
            "statement": (r.statement or "") if r else "", "statement_url": (r.url or "") if r else "",
            "notes": " | ".join(f.notes),
            "restated_from": "; ".join(f"{x.accession}: {x.value:g} ({x.reason})" for x in f.restated_from),
        })
    return out


def payload(run: Run) -> dict:
    recon = {r.fact: r for r in run.reconciliation}
    body = {
        "facts": _fact_rows(run.reported, recon),
        "adjusted_facts": [r for r in _fact_rows(run.adjusted, recon) if r["status"] == "analyst-adjusted"
                           or r["key"] in _changed(run.reported, run.adjusted)],
        "what_if_facts": [r for r in _fact_rows(run.what_if, recon) if r["key"] in _changed(run.reported, run.what_if)],
        "eps_bridge": run.eps_bridge,
        "eps_bridge_what_if": run.eps_bridge_what_if,
        "reconciliation": [r.to_dict() for r in run.reconciliation],
        "review": [i.model_dump() for i in run.reported.review],
        "adjustments": [a.model_dump() | {"resulting": a.resulting} for a in run.adjustments],
        "observations": run.observations,
        "ledger_problems": run.ledger_problems,
        "latest_labels": run.latest_labels,
        "latest_facts": _fact_rows(run.latest, {r.fact: r for r in run.latest_reconciliation}) if run.latest else [],
        "latest_reconciliation": [r.to_dict() for r in run.latest_reconciliation],
    }
    snapshots = sorted({*run.reported.snapshot_ids.values(), *(r.snapshot_id for r in run.reconciliation if r.snapshot_id)})
    return {
        "run": {"ticker": run.ticker, "created_at": run.created_at, "code_version": code_version(), "config": run.config},
        "inputs": {"snapshot_ids": run.reported.snapshot_ids, "all_snapshots_read": snapshots},
        "company": run.reported.company.model_dump(),
        "outputs_digest": outputs_digest(body),
        **body,
    }


def _changed(a: Dataset, b: Dataset) -> set[str]:
    return {k for k, f in b.facts.items() if k in a.facts and a.facts[k].value != f.value}


# ----------------------------------------------------------------------------- markdown


def definitions(ds) -> list[str]:
    """Every distinct formula a derived metric used, with the years it applied to."""
    by: dict[tuple[str, str], list[str]] = {}
    for f in ds.facts.values():
        if f.formula and f.status.value == "derived" and "not presented" not in f.formula:
            by.setdefault((f.metric, f.formula), []).append(f.fiscal_label)
    return [f"| {m} | `{formula}` | {', '.join(sorted(labs))} |" for (m, formula), labs in sorted(by.items())]


def markdown(run: Run, data: dict, peers_md: str = "") -> str:
    ds = run.reported
    lines = {r.fact: r.line for r in run.reconciliation if r.line}
    c = ds.company
    recon_counts: dict[str, int] = {}
    for r in run.reconciliation:
        recon_counts[r.outcome] = recon_counts.get(r.outcome, 0) + 1
    status_counts: dict[str, int] = {}
    for f in ds.facts.values():
        status_counts[f.status.value] = status_counts.get(f.status.value, 0) + 1
    blocks = [i for i in ds.review if i.severity == "block"]
    warns = [i for i in ds.review if i.severity == "warn"]
    fye = f"{c.fiscal_year_end[:2]}-{c.fiscal_year_end[2:]}"
    L = [
        f"# {c.legal_name} ({run.ticker}) — fundamentals dossier",
        "",
        f"Fiscal years {ds.labels[0]}–{ds.labels[-1]} (fiscal year ends {fye}) · run `{data['outputs_digest'][:12]}` · "
        f"code `{data['run']['code_version']['commit'][:8] or 'uncommitted'}`"
        + (" (uncommitted changes)" if data["run"]["code_version"]["dirty"] else "") + f" · created {run.created_at}",
        "",
        f"**Data vintage: {run.config.get('vintage', 'current (latest restated filings)')}.** "
        "Every figure below comes from SEC filings through pinned snapshots and deterministic Python. "
        "`fre verify-run` recomputes this run and proves the digest.",
        "",
        "## Data quality",
        "",
        f"- Facts: " + ", ".join(f"{v} {k}" for k, v in sorted(status_counts.items())),
        f"- Reconciliation to filed statements: " + ", ".join(f"{v} {k}" for k, v in sorted(recon_counts.items())),
        f"- Review queue: {len(blocks)} blocking, {len(warns)} warnings",
        f"- Ledger quotes verified against filing text: " + ("all" if not run.ledger_problems else f"{len(run.ledger_problems)} problems"),
        "",
        "## 1. Is the business growing, and is profitability improving?",
        "",
        *_growth_sentences(ds), "",
        _table(ds, ROWS["growth"], lines=lines),
        "",
        "## 2. Are EPS gains coming from the business, the share count, or unusual items?",
        "",
        *[f"- {s}" for s in _eps_sentences(run)],
        *[f"- {s}" for s in _what_if_sentences(run)],
        "",
        _table(ds, ROWS["eps"], lines=lines),
        "",
        "EPS bridge identity: EPS factor ≈ net-income factor / diluted-share factor (approximation: the "
        "numerator and share basis are not reconciled share class by share class).",
        "",
        "## 3. How much accounting profit becomes cash?",
        "",
        *_cash_sentences(ds), "",
        _table(ds, ROWS["cash"], lines=lines),
        "",
        "## 4. What investment does growth require?",
        "",
        _table(ds, ROWS["investment"], lines=lines),
        "",
        "## 5. Could debt, stock compensation, or accounting choices mislead?",
        "",
        _table(ds, ROWS["quality"], lines=lines),
        "",
        "Debt policy: notes at carrying value + finance leases + commercial paper, every year. Operating leases "
        "are shown but excluded. SBC stays an expense: FCF after SBC is shown beside cash FCF.",
        "",
        "### Accounting review ledger",
        "",
        "| ID | Year | Metric | Original | Adjustment | Result | Status |",
        "|---|---|---|---:|---:|---:|---|",
        *[f"| {a.id} | {a.fiscal_label} | {a.metric} | {money(a.original)} | {money(a.delta)} | {money(a.resulting)} | {a.status} |"
          for a in run.adjustments],
        "",
        *[f"- **{o['id']}** ({', '.join(o['fiscal_labels'])}): {' '.join(o['note'].split())}" for o in run.observations],
        "",
    ]
    L += _latest_section(run)
    if peers_md:
        L += ["## 6. How does it compare with comparable businesses?", "", peers_md, ""]
    L += _thesis_section(run.ticker)
    L += ["## Review queue", ""]
    for i in blocks + warns:
        L.append(f"- **{i.severity}** `{i.kind}` {i.message}")
    if not blocks and not warns:
        L.append("- Nothing open.")
    L += ["", "## Definitions", "", "| Metric | Formula | Years |", "|---|---|---|", *definitions(ds)]
    L += ["", "Reported metrics map to XBRL tags: " + "; ".join(f"{m.id} = {', '.join(m.tags)}" for m in METRICS.values()), "",
          "Legend: † analyst-adjusted, ‼ conflicting (withheld), — missing (not reported), n/a suppressed (formula exists but "
          "an input or denominator does not allow it; the reason is in tables/facts.csv and review.html).", ""]
    return "\n".join(L)


LATEST_ROWS = [("revenue", "Revenue"), ("operating_income", "Operating income"), ("net_income", "Net income"),
               ("equity_securities_gain", "Gains on equity securities"), ("cfo", "Operating cash flow"),
               ("capex", "Capex"), ("fcf", "Cash FCF (CFO - capex)"), ("dna", "Depreciation"), ("sbc", "SBC"),
               ("buybacks", "Buybacks"), ("dividends", "Dividends to common")]
LATEST_BALANCE = [("cash", "Cash"), ("st_investments", "Marketable securities"),
                  ("other_lt_investments", "Other long-term investments"), ("debt_lt_noncurrent", "Long-term debt"),
                  ("debt_lt_current", "Current portion of debt"), ("finance_lease_liability", "Finance leases"),
                  ("preferred_equity", "Preferred stock (carrying)"), ("equity", "Total equity")]


def _latest_section(run: Run) -> list[str]:
    if run.latest is None:
        return ["## Latest reported period", "", "No 10-Q had been filed after the last 10-K in this run's data "
                "(as of its vintage).", ""]
    ds, lab = run.latest, run.latest_labels
    counts: dict[str, int] = {}
    for r in run.latest_reconciliation:
        counts[r.outcome] = counts.get(r.outcome, 0) + 1
    L = [f"## Latest reported period (10-Q through {lab['cur'][3:]})", "",
         "Year-to-date values reconciled to the 10-Q statements (" + ", ".join(f"{v} {k}" for k, v in sorted(counts.items()))
         + "). TTM = last fiscal year + YTD - prior-year YTD, built only from reconciled inputs.", "",
         "| Metric | YTD prior year | YTD current | Change | Latest quarter | TTM |", "|---|---:|---:|---:|---:|---:|"]
    for m, name in LATEST_ROWS:
        a, b, t = ds.value(m, lab["prior"]), ds.value(m, lab["cur"]), ds.value(m, lab["ttm"])
        q = ds.facts.get(f"{m}@{lab.get('q')}")
        qtxt = "—" if q is None else money(q.value) + ("*" if q.status == FactStatus.DERIVED else "")
        ch = pct(b / a - 1, True) if a and b is not None and a > 0 and b >= 0 else "—"
        L.append(f"| {name} | {money(a)} | {money(b)} | {ch} | {qtxt} | {money(t)} |")
    L += ["", "\\* latest quarter derived as YTD minus the prior YTD (cash flow statements report year-to-date only)."]
    L += ["", f"Balance sheet at {lab['bs'][2:]}:", "", "| Item | Amount |", "|---|---:|"]
    L += [f"| {n} | {money(ds.value(m, lab['bs']))} |" for m, n in LATEST_BALANCE]
    L += [f"| Common shares outstanding | {shares(ds.value('shares_outstanding', lab['bs']))} |", ""]
    return L


def _thesis_section(ticker: str) -> list[str]:
    """PRD section 3 Q8: what would change the team's view. Owned by the team; rendered as written."""
    import yaml

    from .pipeline import ROOT
    p = ROOT / "reviews" / ticker / "thesis.yaml"
    if not p.exists():
        return []
    t = yaml.safe_load(p.read_text()) or {}
    L = ["## 7. Thesis and what would change it (team-owned)", "",
         f"- Claim: {t.get('claim') or '**not written yet**'}",
         f"- Direction: {t.get('direction') or '**not set**'} · owner: {t.get('owner') or '**none**'}"]
    for key, name in (("counterevidence", "Counterevidence"), ("invalidation", "Would change our view if"),
                      ("decision_history", "Decision history")):
        vals = t.get(key) or []
        L.append(f"- {name}: " + ("; ".join(str(v) for v in vals) if vals else "**empty**"))
    L += ["- Research questions: " + " / ".join(t.get("research_questions") or []), ""]
    return L


def write(run: Run, out_root: Path, peers_md: str = "") -> Path:
    data = payload(run)
    out = out_root / run.ticker / data["outputs_digest"][:12]
    (out / "tables").mkdir(parents=True, exist_ok=True)
    (out / "run.json").write_text(json.dumps(data, indent=2, sort_keys=True, default=str))
    (out / "dossier.md").write_text(markdown(run, data, peers_md))
    for name in ("facts", "adjusted_facts", "what_if_facts", "reconciliation", "review", "adjustments", "eps_bridge"):
        rows = data[name]
        if not rows:
            continue
        cols = list(dict.fromkeys(k for r in rows for k in r))
        with open(out / "tables" / f"{name}.csv", "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=cols)
            w.writeheader()
            for r in rows:
                w.writerow({k: (json.dumps(v) if isinstance(v, (list, dict)) else v) for k, v in r.items()})
    return out
